# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('alert', models.BooleanField(default=False)),
            ],
        ),
    ]
