version: "3.0"
services:
  db: 
    restart: always
    image: postgres

  web:
    build: 
      context: .
    command: python3 manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db